included:
  - Sources
  - Tests
disabled_rules:
  - colon
  - vertical_whitespace
  - trailing_whitespace
  - statement_position
  - trailing_comma
  - nesting
  - private_over_fileprivate
opt_in_rules:
  - cyclomatic_complexity
